CREATE DATABASE USERDB;
GO

USE USERDB;
GO

CREATE TABLE NGUOIDUNG
(
ID INT IDENTITY(1,1) PRIMARY KEY,
USERNAME NVARCHAR(50) NOT NULL UNIQUE,
EMAIL NVARCHAR(100) NULL UNIQUE,
PHONE NVARCHAR(20) NULL UNIQUE,
PASSWORDHASH NVARCHAR(64) NOT NULL,
SALT NVARCHAR(50) NOT NULL
)